### ISSUE TITLE
unable to install using readme instructions.

### ISSUE THREAD

**Issue by jeremychia** [a-chacon/awesome-jekyll-theme#1]
referencing: https://github.com/a-chacon/awesome-jekyll-theme/commit/9fb32334557b04fd6df9e129adb2ca79a0f94794

i was unable to successfully install the theme and deploy it as a github page.
so to save some effort, i decided to fork the repository instead.

is there a more foolproof (or beginners' way) to do this?

**Comment by a-chacon** [comment]
Hey! Yes, I looked at your fork, so I decided to add more info. But I still think it is incomplete.

Your way is ok, but you get the theme with data that you don't use (ex: some test posts, projects and configs) and then if I make updates you will not have these (Or maybe yes, merging it).

I will be working to document it. And I will be checking other themes to know how they do it.

**Comment by jeremychia** [comment]
thanks a lot! :relaxed: yes. i forked it as a way of acknowledging that it's a base template from what you had. thanks so much for creating it - i really like this theme.

**Comment by a-chacon** [comment]
@jeremychia You are welcome! I think now is well explained (With the help of AI 😅). Please feel free to open a new issue if you find something else.
