### ISSUE TITLE
Contact Channels Shows Without Config

### ISSUE THREAD

**Issue by Urchmaney** [a-chacon/awesome-jekyll-theme#13]
Hello,

Thanks for your awesome jekyll gem. I am having some issue with the configuration.
I don't have telegram or discord but it shows up. I fixed this by overriding it.  Wanted to bring it to your notice if you would add it to be a default setting.

To be more clear,

```
rrss:
  github: "...."
```
With the above configuration, I want only github to show up.

**Comment by a-chacon** [comment]
Hello, thanks to you for been using it and report this behavior. I think you are right, so I will be looking a solution for this soon.

**Comment by a-chacon** [comment]
Yes, I know how I can fix this, but there's a problem. I use the _config.yml file for both the gem and the GitLab page (which is an example site). If I remove the default contact channels, the example page won't feel as realistic, you know? But I'll try to make some adjustments when building the gem or maybe host the example page in a separate repo.

**Comment by Urchmaney** [comment]
Nice. I will update and give you any feedback. Thanks for your efforts 😌.
